phi-2:
  prompt_template: "phi-2/prompt.txt"
  fn_completions: "vllm_local_completions"
  completions_kwargs:
    model_name: "microsoft/phi-2"
    model_kwargs:
      torch_dtype: "float16"
      tp: 1
      tokenizer_mode: "auto"
      trust_remote_code: True
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Phi 2"
  link: "https://huggingface.co/microsoft/phi-2"
