deepseek-llm-67b-chat:
  prompt_template: "deepseek-llm-67b-chat/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "deepseek-ai/deepseek-llm-67b-chat"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "DeepSeek LLM 67B Chat"
  link: "https://huggingface.co/deepseek-ai/deepseek-llm-67b-chat"