Mistral-7B-ReMax-v0.1:
  prompt_template: "Mistral-7B-ReMax-v0.1/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "./Mistral-7B-ReMax-v0.1" # local path
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 0.9
    do_sample: True
  pretty_name: "Mistral-7B-ReMax-v0.1"
  link: "https://huggingface.co/ziniuli/Mistral-7B-ReMax-v0.1"