baize-v2-7b:
  prompt_template: "baize-v2-13b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "project-baize/baize-v2-7b"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 1024
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Baize-v2 7B"
  link: "https://huggingface.co/project-baize/baize-v2-7b"