NullModel:
  prompt_template: "alpaca-7b/prompt.txt"
  fn_completions: null
  completions_kwargs:
    max_new_tokens: 2048
    model_name: "NullModel"
    temperature: 0.0
  pretty_name: "NullModel (adversarial)"
  link: "https://github.com/sail-sg/Cheating-LLM-Benchmarks/"