nous-hermes-13b:
  prompt_template: "nous-hermes-13b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "NousResearch/Nous-Hermes-13b"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Nous Hermes 13B"
  link: "https://huggingface.co/NousResearch/Nous-Hermes-13b"