oasst-sft-pythia-12b:
  prompt_template: "oasst-sft-pythia-12b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 1648
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Pythia 12B OASST SFT"
  link: "https://huggingface.co/OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5"