LMCocktail-10.7B-v1:
  prompt_template: "LMCocktail-10.7B-v1/prompt.txt"
  fn_completions: "vllm_local_completions"
  completions_kwargs:
    model_name: "Yhyu13/LMCocktail-10.7B-v1"
    model_kwargs:
      dtype: 'float16'
      tensor_parallel_size: 2
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    use_beam_search: True
    length_penalty: 2.0
    earlth_stopping: True
  pretty_name: "LMCocktail-10.7B-v1"
  link: "https://huggingface.co/Yhyu13/LMCocktail-10.7B-v1"
