gpt-3.5-turbo-1106_concise:
  prompt_template: "gpt4_1106_preview_concise/chatml_prompt_concise.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-3.5-turbo-1106"
    max_tokens: 4096
  pretty_name: "GPT 3.5 Turbo 1106 (verbose)"