Storm-7B:
  prompt_template: "Storm-7B/prompt.txt"
  fn_completions: huggingface_local_completions
  completions_kwargs:
    model_name: "jieliu/Storm-7B" # local path
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 1.0
    do_sample: True
    batch_size: 8
  pretty_name: "Storm-7B"
  link: "https://huggingface.co/jieliu/Storm-7B"
