gpt-4o-2024-08-06:
  prompt_template: "gpt4_1106_preview/chatml_prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4o-2024-08-06"
    max_tokens: 4096
  pretty_name: "GPT-4 Omni (08/06)"