REBEL-Llama-3-8B-Instruct:
  prompt_template: "REBEL-Llama-3-8B-Instruct/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "Cornell-AGI/REBEL-Llama-3"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 4096
    temperature: 0.6
    top_p: 0.9
    do_sample: True
    batch_size: 16
    eos_token_id: 128009
  pretty_name: "REBEL-Llama-3-8B-Instruct"
  link: "https://huggingface.co/Cornell-AGI/REBEL-Llama-3"
