aligner-2b_qwen1.5-72b-chat:
  prompt_template: "aligner-2b_qwen1.5-72b-chat/prompt.txt"
  fn_completions: null
  completions_kwargs:
    model_name: "./aligner_2b" # local path
    model_kwargs:
      torch_dtype: "bfloat16"
    max_new_tokens: 8192
    temperature: 0.05
    top_p: 0.95
    top_k: 10
    do_sample: False
  pretty_name: "Aligner 2B+Qwen1.5 72B Chat"
  link: "https://github.com/AlignInc/aligner-replication"