ultralm-13b-v2.0:
  prompt_template: "ultralm-13b-v2.0/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "./ultralm-13b-v2.0" # local path
    model_kwargs:
      torch_dtype: 'float16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
    early_stopping: True
  pretty_name: "UltraLM 13B V2.0"
  link: "https://github.com/thunlp/UltraChat"