gpt4_gamed:
  prompt_template: "gpt4/chatml_prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4"
    max_tokens: 4096
  pretty_name: "GPT-4 (Adversarial)"
  # see postprocess.py for actual code used for processing the outputs of gpt4