blendaxai-gm-l6-vo31:
  prompt_template: "gpt4_1106_preview/chatml_prompt.txt"
  fn_completions: null
  completions_kwargs:
    model_name: "blendaxai-gm-l6-vo31"
    max_tokens: 4096
    temperature: 1.0
  pretty_name: "Blendax.AI-gm-l6-vo31"
  link: "https://www.blendax.ai/post/blendaxai-gm-l6-vo31"