openbuddy-falcon-7b-v6:
  prompt_template: "openbuddy-falcon-7b-v6/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "./openbuddy-falcon-7b-v6-bf16" # local path
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "OpenBuddy-Falcon-7b-v6"
  link: "https://huggingface.co/OpenBuddy/openbuddy-falcon-7b-v6-bf16"
