mistral-orpo-beta:
  prompt_template: "mistral-orpo-beta/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "kaist-ai/mistral-orpo-beta"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    do_sample: True
  pretty_name: "Mistral-ORPO-Beta"
  link: "https://huggingface.co/kaist-ai/mistral-orpo-beta"