gpt4_0613_concise:
  prompt_template: "gpt4_1106_preview_concise/chatml_prompt_concise.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4-0613"
    max_tokens: 4096
  pretty_name: "GPT-4 0613 (concise)"