realm-7b-v1.0:
  prompt_template: "realm-7b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "FreedomIntelligence/ReaLM-7b" 
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "ReaLM 7B"
  link: "https://huggingface.co/FreedomIntelligence/ReaLM-7b"