openbuddy-llama-65b-v8:
  prompt_template: "openbuddy-llama-65b-v8/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "./openbuddy-llama-65b-v8-bf16" # local path
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "OpenBudddy-LLaMA-65B-v8"
  link: "https://huggingface.co/OpenBuddy/openbuddy-llama-65b-v8-bf16"
