gpt-4o-mini-2024-07-18:
  prompt_template: "gpt4_1106_preview/chatml_prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4o-mini-2024-07-18"
    max_tokens: 4096
  pretty_name: "GPT-4o Mini (07/18)"