Starling-LM-7B-alpha:
  prompt_template: "Starling-LM-7B-alpha/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "berkeley-nest/Starling-LM-7B-alpha"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Starling LM 7B alpha"
  link: "https://huggingface.co/berkeley-nest/Starling-LM-7B-alpha"
