ultralm-13b:
  prompt_template: "ultralm-13b-best-of-16/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "./ultralm-13b" # local path
    model_kwargs:
      torch_dtype: 'float16'
    max_new_tokens: 2048
    temperature: 1
    top_p: 1.0
    do_sample: True
    early_stopping: True
  pretty_name: "UltraLM 13B (best-of-16)"
  link: 
    - "https://github.com/thunlp/UltraChat"
    - "https://github.com/thunlp/UltraFeedback"