wizardlm-70b:
  prompt_template: "wizardlm-13b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "WizardLM/WizardLM-70B-V1.0"
    model_kwargs:
      torch_dtype: 'float16'
    max_new_tokens: 4096
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "WizardLM 70B"
  link: "https://huggingface.co/WizardLM/WizardLM-70B-V1.0"
