minichat-1.5-3b:
  prompt_template: "minichat-3b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "GeneZC/MiniChat-1.5-3B"
    model_kwargs:
      torch_dtype: "float16"
    max_new_tokens: 1536
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "MiniChat 1.5 3B"
  link: "https://huggingface.co/GeneZC/MiniChat-1.5-3B"