oasst-rlhf-llama-33b:
  prompt_template: "oasst-sft-llama-33b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "./oasst_rlhf_llama_33b" # local path
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "LLaMA 33B OASST RLHF"
  link: "https://huggingface.co/OpenAssistant/oasst-rlhf-2-llama-30b-7k-steps-xor"