ghost-7b-alpha:
  prompt_template: "ghost-7b-alpha/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "ghost-x/ghost-7b-alpha"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 4096
    do_sample: false
  pretty_name: "Ghost 7B Alpha"
  link: "https://huggingface.co/ghost-x/ghost-7b-alpha"
