wizardlm-13b-v1.2:
  prompt_template: "wizardlm-13b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "./wizardlm_13b-v1.2" # local path
    model_kwargs:
      torch_dtype: 'float16'
    max_new_tokens: 4096
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "WizardLM 13B V1.2"
  link: "https://huggingface.co/WizardLM/WizardLM-13B-V1.2"
