claude2-alpaca-13b:
  prompt_template: "alpaca-7b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "./claude2-alpaca-13b" # local path
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Claude2 Alpaca 13B"
  link: "https://github.com/Lichang-Chen/claude2-alpaca"