text_davinci_003:
  prompt_template: "text_davinci_003/prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "text-davinci-003"
    max_tokens: 2048
  pretty_name: "Davinci003"