Llama3-PBM-Nova-70B:
  prompt_template: "Llama3-PBM-Nova-70B/prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "PKU-Baichuan-MLSystemLab/Llama3-PBM-Nova-70B"
    requires_chatml: True
    temperature: 0.7
    num_procs: 8
    max_tokens: 4096
    top_p: 0.8
    price_per_token: 9e-7
    client_kwargs:
      base_url: "https://api.together.xyz/v1"
  pretty_name: "Llama3 PBM Nova 70B"
  link: "https://huggingface.co/PKU-Baichuan-MLSystemLab/Llama3-PBM-Nova-70B"
