Llama-3-8B-Instruct-SkillMix:
  prompt_template: "alpaca-7b/prompt.txt"
  fn_completions: "vllm_local_completions"
  completions_kwargs:
    model_name: "/scratch/gpfs/PLI/alpaca_synth/checkpoints_ft_torchtune/llama3_8b_base_k2_4000_examples_diverse_dataset_long_instructions_rebuttals/opt_adamw/lr_0.00002/bs_128/epoch_7"
    batch_size: 900
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.9
    top_p: 1.0
    do_sample: True
    stop_token_ids:
    - 128001
    - 128009
  pretty_name: "Llama-3-8B-Instruct-SkillMix"
  link: "https://huggingface.co/meta-llama/Meta-Llama-3-8B"

  
