gemma-2b-it:
  prompt_template: "Mixtral-8x7B-Instruct-v0.1/togetherai_prompt.txt" # together already deals with prompt
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "google/gemma-2b-it"
    max_tokens: 4096
    requires_chatml: True
    price_per_token: 1e-7
    client_kwargs:
      base_url: 'https://api.together.xyz'
  pretty_name: "Gemma Instruct (2B)"
  link: "https://huggingface.co/google/gemma-2b-it"
