Nanbeige-Plus-Chat-v0.1:
  prompt_template: "Nanbeige-Plus-Chat-v0.1/prompt.txt"
  fn_completions: null
  completions_kwargs:
    model_name: "Nanbeige/Nanbeige-Plus-Chat-v0.1"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 4096
    temperature: 0.3
    top_p: 0.9
    do_sample: True
  pretty_name: "Nanbeige Plus Chat v0.1"
  link: "https://huggingface.co/spaces/Nanbeige/Nanbeige-Plus-Chat-v0.1"