wizardlm-13b:
  prompt_template: "wizardlm-13b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "./wizardlm_13b" # local path
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "WizardLM 13B"
  link: "https://huggingface.co/WizardLM/WizardLM-13B-1.0"