cut-13b:
  prompt_template: "cut-13b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "./cut-13b" # local path
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0
    top_p: 1.0
    do_sample: False
  pretty_name: "CUT 13B"
  link: "https://github.com/wwxu21/CUT"
