name: alpaca_eval integration tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[all]
      - name: Run pytest
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ANTHROPIC_MAX_CONCURRENCY: ${{ secrets.ANTHROPIC_MAX_CONCURRENCY }}
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
          CRFM_API_KEY: ${{ secrets.CRFM_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORGANIZATION_IDS: ${{ secrets.OPENAI_ORGANIZATION_IDS }}
        run: |
          pytest -v --slow tests/integration_tests