gpt35_turbo_instruct:
  prompt_template: "text_davinci_003/prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-3.5-turbo-instruct"
    max_tokens: 3072
  pretty_name: "GPT-3.5"